services:
  airflow:
    image: apache/airflow:2.9.3
    container_name: airflow
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__EXECUTOR: "SequentialExecutor"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      # Paquetes extra solo para la demo
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas==2.2.2"
    env_file:
      - .env
    user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: bash -lc "airflow db migrate && airflow scheduler & exec airflow webserver"

